pegasus_model_path = ""
finetune_pegasus_train_text = "data/dataset/LCSTS/train.src.txt"
finetune_pegasus_train_label = "data/dataset/LCSTS/train.tgt.txt"
train_model_template = "data/model/template"
save_finetune_pegasus_summary = "data/model/finetune_pegasus_summary"